name: ${project.name}
main: net.plazmix.bukkitauth.PlazmixBukkitAuthPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

author: PlazmixDevelopmentTeam

depend: [PlazmixAPI]
